spring:
  application:
    name: 'search-service'
  config:
    import: classpath:SearchServiceConfig.yml

  h2:
    console:
      enabled: true
      path: ${H2_PATH:/h2}
      settings:
        web-allow-others: true

  datasource:
    url: ${DB_URL:jdbc:h2:mem:search-app}
    username: sa
    password:


server:
  port: ${PORT_NUMBER:8080}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
