api:
#  baseUrl: http://localhost:8081/
  baseUrl: http://google-service:8081/
  apiPath: api/search?query=

## H2 DATABASE ##
#DB_URL: jdbc:h2:mem:search-app
#DB_USERNAME: sa
#DB_PASSWORD:

## MONGO DB DATABASE ##
MONGODB_URI: mongodb://host.docker.internal:27017/search-serv

## PostgreSQL DATABASE ##
#DB_URL: jdbc:postgresql://localhost:5432/searchserv
#DB_URL: jdbc:postgresql://host.docker.internal:5432/searchserv
#DB_USERNAME: postgres
#DB_PASSWORD: postgres
#DRIVER_CLASS_NAME: org.postgresql.Driver

## SQL SERVER DATABASE ##
#DB_URL: jdbc:sqlserver://localhost:1433;databaseName=search-serv;encrypt=true;trustServerCertificate=true
DB_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=search-serv;encrypt=true;trustServerCertificate=true
DB_USERNAME: Norpix
DB_PASSWORD: sa123
DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver