/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.search.project.kafka.response.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SearchResultsListDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3037883237150765906L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SearchResultsListDto\",\"namespace\":\"com.search.project.kafka.response.avro.model\",\"fields\":[{\"name\":\"searchResultsListDto\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SearchResultsDto\",\"fields\":[{\"name\":\"title\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"link\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SearchResultsListDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SearchResultsListDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SearchResultsListDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SearchResultsListDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SearchResultsListDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SearchResultsListDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SearchResultsListDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SearchResultsListDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SearchResultsListDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> searchResultsListDto;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SearchResultsListDto() {}

  /**
   * All-args constructor.
   * @param searchResultsListDto The new value for searchResultsListDto
   */
  public SearchResultsListDto(java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> searchResultsListDto) {
    this.searchResultsListDto = searchResultsListDto;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return searchResultsListDto;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: searchResultsListDto = (java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'searchResultsListDto' field.
   * @return The value of the 'searchResultsListDto' field.
   */
  public java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> getSearchResultsListDto() {
    return searchResultsListDto;
  }


  /**
   * Sets the value of the 'searchResultsListDto' field.
   * @param value the value to set.
   */
  public void setSearchResultsListDto(java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> value) {
    this.searchResultsListDto = value;
  }

  /**
   * Creates a new SearchResultsListDto RecordBuilder.
   * @return A new SearchResultsListDto RecordBuilder
   */
  public static com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder newBuilder() {
    return new com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder();
  }

  /**
   * Creates a new SearchResultsListDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SearchResultsListDto RecordBuilder
   */
  public static com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder newBuilder(com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder other) {
    if (other == null) {
      return new com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder();
    } else {
      return new com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder(other);
    }
  }

  /**
   * Creates a new SearchResultsListDto RecordBuilder by copying an existing SearchResultsListDto instance.
   * @param other The existing instance to copy.
   * @return A new SearchResultsListDto RecordBuilder
   */
  public static com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder newBuilder(com.search.project.kafka.response.avro.model.SearchResultsListDto other) {
    if (other == null) {
      return new com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder();
    } else {
      return new com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for SearchResultsListDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SearchResultsListDto>
    implements org.apache.avro.data.RecordBuilder<SearchResultsListDto> {

    private java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> searchResultsListDto;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.searchResultsListDto)) {
        this.searchResultsListDto = data().deepCopy(fields()[0].schema(), other.searchResultsListDto);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SearchResultsListDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.search.project.kafka.response.avro.model.SearchResultsListDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.searchResultsListDto)) {
        this.searchResultsListDto = data().deepCopy(fields()[0].schema(), other.searchResultsListDto);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'searchResultsListDto' field.
      * @return The value.
      */
    public java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> getSearchResultsListDto() {
      return searchResultsListDto;
    }


    /**
      * Sets the value of the 'searchResultsListDto' field.
      * @param value The value of 'searchResultsListDto'.
      * @return This builder.
      */
    public com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder setSearchResultsListDto(java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> value) {
      validate(fields()[0], value);
      this.searchResultsListDto = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'searchResultsListDto' field has been set.
      * @return True if the 'searchResultsListDto' field has been set, false otherwise.
      */
    public boolean hasSearchResultsListDto() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'searchResultsListDto' field.
      * @return This builder.
      */
    public com.search.project.kafka.response.avro.model.SearchResultsListDto.Builder clearSearchResultsListDto() {
      searchResultsListDto = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SearchResultsListDto build() {
      try {
        SearchResultsListDto record = new SearchResultsListDto();
        record.searchResultsListDto = fieldSetFlags()[0] ? this.searchResultsListDto : (java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SearchResultsListDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<SearchResultsListDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SearchResultsListDto>
    READER$ = (org.apache.avro.io.DatumReader<SearchResultsListDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.searchResultsListDto.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.search.project.kafka.response.avro.model.SearchResultsDto e0: this.searchResultsListDto) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> a0 = this.searchResultsListDto;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto>((int)size0, SCHEMA$.getField("searchResultsListDto").schema());
        this.searchResultsListDto = a0;
      } else a0.clear();
      SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.search.project.kafka.response.avro.model.SearchResultsDto e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.search.project.kafka.response.avro.model.SearchResultsDto();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.search.project.kafka.response.avro.model.SearchResultsDto> a0 = this.searchResultsListDto;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto>((int)size0, SCHEMA$.getField("searchResultsListDto").schema());
            this.searchResultsListDto = a0;
          } else a0.clear();
          SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.search.project.kafka.response.avro.model.SearchResultsDto>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.search.project.kafka.response.avro.model.SearchResultsDto e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.search.project.kafka.response.avro.model.SearchResultsDto();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










